# Generated by Django 4.1.2 on 2023-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Jenis', models.CharField(max_length=100)),
                ('Harga', models.CharField(max_length=100)),
            ],
        ),
    ]
